language: 'en-US'
early_access: false
reviews:
  high_level_summary: true
  poem: false
  review_status: false
  changed_files_summary: true
  sequence_diagrams: false
  assess_linked_issues: true
  path_filters:
    - '!**/*.lock'
    - '!go.mod'
    - '!go.sum'
  auto_review:
    enabled: false
    drafts: false
chat:
  auto_reply: true
