# Enable colors or not. Prefer setting NO_COLOR or -C over
# using this option to ensure colors always match even
# in case of errors.
color = true
# Where to look for configuration by default
config_location = "/etc/nixos"
# Disable confirmation dialogs. This is good for ensuring
# that commands will run to completion without user input.
no_confirm = false
# Command to use to promote process to root
root_comand = "sudo"
# Use `nvd` (https://gitlab.com/khumba/nvd) instead of
# `nix store diff-closures` when showing closure diffs
use_nvd = false

# Aliases for long commands that you don't want to type out. All arguments
# after the aliases are passed as-is to the underlying command.
# Aliases must not contain spaces.
# Aliases are resolved to a series of arguments, as a list of strings.
[aliases]
genlist = ["generation", "list"]
switch = ["generation", "switch"]
rollback = ["generation", "rollback"]

# Configuration for the `apply` subcommand.
[apply]
# Name of specialisation to use by default
specialisation = ""
# Use `nix-output-monitor` as an alternative `nix build` front-end
use_nom = false
# This only applies for flake configurations, and is always true in the
# case of legacy configurations.
imply_impure_with_tag = false
# Use the Git commit message as the description tag for the
# generation automatically if a tag is not provided.
# This setting does not work with dirty Git trees.
use_git_commit_msg = false
# Ignore dirty working tree when using Git commit message for --tag.
# This may result in generation descriptions that don't match the
# commit history, so only use this if you are judicious about using
# Git commits for configuration changes.
ignore_dirty_tree = false

# Configuration for the `enter` subcommand.
[enter]
# Bind-mount the host `resolv.conf` inside the chroot for internet access
mount_resolv_conf = true

# Configuration for the `init` subcommand. This is managed by `nixpkgs`, and
# normally should not be touched unless you know what you are doing.
[init]
# Generate options to enable X11 display server
enable_xserver = false
# Configuration options for a desktop environment to include by default
desktop_config = ""
# Extra configuration to append to `configuration.nix` as a string
extra_config = ""

# Configuration for the `option` subcommand.
[option]
# Minimum distance score to consider an option a match. This can be any number,
# including negative numbers. Lower scores will give less relevant (but more)
# results, while higher scores will give more relevant results while being
# harder to filter initially.
min_score = 0
# Attempt to prettify option descriptions with colors and formatting.
prettify = true

# Extra configuration to append to `configuration.nix`,
# as structured key-value pairs
[init.extra_attrs]
hello = "\"world\""
